# -*- coding: utf-8 -*-
import matplotlib
# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QTimer
from PyQt5.QtCore import QThread
import time
import matplotlib.pyplot as plt


class FileReaderThread(QThread):
    data_updated = QtCore.pyqtSignal(list)

    def run(self):
        while True:
            try:
                with open('output.txt', 'r') as file:
                    data = file.readlines()
                    if len(data) >= 20:  # Assuming there are 11 lines of data in the file
                        self.data_updated.emit([line.strip() for line in data])
            except FileNotFoundError:
                print("File not found")
            time.sleep(0.05)  # Adjust the interval as needed

class Ui_MainWindow(object):
    def slot_figure_pressed(self):
        with open('drone_data.txt', 'r') as file:
            lines = file.readlines()

        motor1_speeds = []
        motor2_speeds = []
        motor3_speeds = []
        motor4_speeds = []
        times = []

        for line in lines:
            if line.startswith('motor'):
                parts = line.split(':')
                speeds = parts[1].strip()
                motor_speed = speeds.split(',')
                if len(motor_speed) == 4:
                    motor1_speeds.append(int(motor_speed[0]))
                    motor2_speeds.append(int(motor_speed[1]))
                    motor3_speeds.append(int(motor_speed[2]))
                    motor4_speeds.append(int(motor_speed[3]))
            elif line.startswith('time'):
                times.append(int(line.split(':')[1]))

        # print(motor1_speeds)


        plt.figure(figsize=(20, 10))
        plt.plot(times, motor1_speeds, label='Motor 1')
        plt.plot(times, motor2_speeds, label='Motor 2')
        plt.plot(times, motor3_speeds, label='Motor 3')
        plt.plot(times, motor4_speeds, label='Motor 4')


        plt.ylim(-1500, 1500)

        plt.xlabel('Time')
        plt.ylabel('Speed')
        plt.title('Motor Speeds Over Time')
        plt.legend()
        plt.grid(True)
        plt.show()


    def slot_raw_figure_pressed(self):
        with open('drone_data.txt', 'r') as file:
            lines = file.readlines()

        yaw = []
        pitch = []
        roll = []
        times = []

        for line in lines:
            if line.startswith('raw_ypr'):
                parts = line.split(':')
                speeds = parts[1].strip()
                raw = speeds.split(',')
                if len(raw) == 3:
                    yaw.append(float(raw[0]))
                    pitch.append(float(raw[1]))
                    roll.append(float(raw[2]))
            elif line.startswith('time'):
                times.append(int(line.split(':')[1]))


        plt.figure(figsize=(20, 10))
        plt.plot(times, yaw, label='RAW-YAW')
        plt.plot(times, pitch, label='RAW-PITCH')
        plt.plot(times, roll, label='RAW-ROLL')


        plt.ylim(-10, 10)

        plt.xlabel('Time')
        plt.ylabel('YPR')
        plt.title('RAW YPR Over Time')
        plt.legend()
        plt.grid(True)
        plt.show()
    def slot_speed_figure_pressed(self):
        with open('drone_data.txt', 'r') as file:
            lines = file.readlines()

        yaw = []
        speed = []
        times = []

        for line in lines:
            if line.startswith('raw_ypr'):
                parts = line.split(':')
                speeds = parts[1].strip()
                raw = speeds.split(',')
                if len(raw) == 3:
                    yaw.append(float(raw[0]))
            elif line.startswith('time'):
                times.append(int(line.split(':')[1]))
            elif line.startswith('raw_speed'):
                speed.append(float(line.split(':')[1]))


        plt.figure(figsize=(20, 10))
        plt.plot(times, yaw, label='FILTERED_YAW')
        plt.plot(times, speed, label='RAW-YAW')


        plt.ylim(-50, 50)

        plt.xlabel('Time')
        plt.ylabel('YPR')
        plt.title('RAW and Filter Over Time')
        plt.legend()
        plt.grid(True)
        plt.show()
    def slot_ypr_figure_pressed(self):
        with open('drone_data.txt', 'r') as file:
            lines = file.readlines()

        yaw = []
        pitch = []
        roll = []
        raw_yaw = []
        raw_pitch = []
        raw_roll = []
        times = []

        for line in lines:
            if line.startswith('ypr'):
                parts = line.split(':')
                ypr_data = parts[1].strip()
                ypr = ypr_data.split(',')
                if len(ypr) == 3:
                    yaw.append(float(ypr[0]))
                    pitch.append(float(ypr[1]))
                    roll.append(float(ypr[2]))
            elif line.startswith('raw_ypr'):
                parts = line.split(':')
                raw_data = parts[1].strip()
                raw = raw_data.split(',')
                if len(raw) == 3:
                    raw_yaw.append(float(raw[0]))
                    raw_pitch.append(float(raw[1]))
                    raw_roll.append(float(raw[2]))
            elif line.startswith('time'):
                times.append(int(line.split(':')[1]))


        plt.figure(figsize=(20, 10))
        plt.plot(times, yaw, label='YAW')
        plt.plot(times, pitch, label='PITCH')
        plt.plot(times, roll, label='ROLL')
        plt.plot(times, raw_yaw, label='RAW-YAW')
        plt.plot(times, raw_pitch, label='RAW-PITCH')
        plt.plot(times, raw_roll, label='RAW-ROLL')


        plt.ylim(-5, 5)

        plt.xlabel('Time')
        plt.ylabel('YPR')
        plt.title('YPR Over Time')
        plt.legend()
        plt.grid(True)
        plt.show()

    def slot_yaw_p_moved(self, value):
        print("yaw_p:",value)
        # sys.stdout.write("1")
        sys.stdout.flush()
    def slot_yaw_d_moved(self, value):
        print("yaw_d:",value)
        # sys.stdout.write("1")
        sys.stdout.flush()

    def slot_pitch_p_moved(self, value):
        print("pitch_p:",value)
        # sys.stdout.write("1")
        sys.stdout.flush()
    def slot_pitch_d_moved(self, value):
        print("pitch_d:",value)
        # sys.stdout.write("1")
        sys.stdout.flush()
    def slot_roll_p_moved(self, value):
        print("roll_p:",value)
        # sys.stdout.write("1")
        sys.stdout.flush()
    def slot_roll_d_moved(self, value):
        print("roll_d:",value)
        # sys.stdout.write("1")
        sys.stdout.flush()


    def slot_safe_pressed(self):
        print("Safe button pressed")
        # sys.stdout.write("1")
        sys.stdout.flush()

    def slot_panic_pressed(self):
        print("Panic button pressed")
        sys.stdout.flush()

    def slot_raw_pressed(self):
        print("Raw button pressed")
        sys.stdout.flush()
    def slot_log_pressed(self):
        print("Log button pressed")
        sys.stdout.flush()
    def slot_manual_pressed(self):
        print("Manual button pressed")
        sys.stdout.flush()

    def slot_yaw_pressed(self):
        print("Yaw button pressed")
        sys.stdout.flush()

    def slot_calibration_pressed(self):
        print("Calibration button pressed")
        sys.stdout.flush()

    def slot_full_pressed(self):
        print("Full button pressed")
        sys.stdout.flush()

    def slot_exit(self):
        print("exit")
        sys.stdout.flush()

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 480)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.JoyPitch = QtWidgets.QLineEdit(self.centralwidget)
        self.JoyPitch.setGeometry(QtCore.QRect(90, 70, 101, 25))
        self.JoyPitch.setObjectName("JoyPitch")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 30, 66, 17))
        self.label_2.setObjectName("label_2")
        self.JoyRoll = QtWidgets.QLineEdit(self.centralwidget)
        self.JoyRoll.setGeometry(QtCore.QRect(90, 110, 101, 25))
        self.JoyRoll.setObjectName("JoyRoll")
        self.DR = QtWidgets.QLineEdit(self.centralwidget)
        self.DR.setGeometry(QtCore.QRect(490, 110, 113, 25))
        self.DR.setObjectName("DR")
        self.JoyYaw = QtWidgets.QLineEdit(self.centralwidget)
        self.JoyYaw.setGeometry(QtCore.QRect(90, 30, 101, 25))
        self.JoyYaw.setObjectName("JoyYaw")
        self.DT = QtWidgets.QLineEdit(self.centralwidget)
        self.DT.setGeometry(QtCore.QRect(490, 150, 113, 25))
        self.DT.setObjectName("DT")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 80, 66, 17))
        self.label_3.setObjectName("label_3")
        self.joyT = QtWidgets.QLineEdit(self.centralwidget)
        self.joyT.setGeometry(QtCore.QRect(90, 150, 101, 25))
        self.joyT.setObjectName("joyT")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(20, 160, 66, 17))
        self.label_10.setObjectName("label_10")
        self.Joylabel = QtWidgets.QLabel(self.centralwidget)
        self.Joylabel.setGeometry(QtCore.QRect(80, 0, 101, 16))
        self.Joylabel.setObjectName("Joylabel")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(400, 110, 31, 17))
        self.label_8.setObjectName("label_8")
        self.pushButtonSafe = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonSafe.setGeometry(QtCore.QRect(540, 190, 88, 25))
        self.pushButtonSafe.setObjectName("pushButtonSafe")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(210, 400, 66, 17))
        self.label_9.setObjectName("label_9")
        self.pushButtonMannul = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonMannul.setGeometry(QtCore.QRect(540, 250, 88, 25))
        self.pushButtonMannul.setObjectName("pushButtonMannul")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(400, 30, 41, 17))
        self.label_5.setObjectName("label_5")
        self.DY = QtWidgets.QLineEdit(self.centralwidget)
        self.DY.setGeometry(QtCore.QRect(490, 30, 113, 25))
        self.DY.setObjectName("DY")
        self.Dronelabel = QtWidgets.QLabel(self.centralwidget)
        self.Dronelabel.setGeometry(QtCore.QRect(470, 0, 101, 16))
        self.Dronelabel.setObjectName("Dronelabel")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(400, 150, 66, 17))
        self.label_11.setObjectName("label_11")
        self.DP = QtWidgets.QLineEdit(self.centralwidget)
        self.DP.setGeometry(QtCore.QRect(490, 70, 113, 25))
        self.DP.setObjectName("DP")
        self.pushButtonPanic = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonPanic.setGeometry(QtCore.QRect(540, 220, 88, 25))
        self.pushButtonPanic.setObjectName("pushButtonPanic")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 120, 66, 17))
        self.label_4.setObjectName("label_4")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(400, 70, 41, 17))
        self.label_6.setObjectName("label_6")
        self.DroneMode = QtWidgets.QLabel(self.centralwidget)
        self.DroneMode.setGeometry(QtCore.QRect(270, 400, 131, 20))
        self.DroneMode.setText("")
        self.DroneMode.setObjectName("DroneMode")
        self.Motor = QtWidgets.QLabel(self.centralwidget)
        self.Motor.setGeometry(QtCore.QRect(320, 0, 66, 17))
        self.Motor.setObjectName("Motor")
        self.Motor_1 = QtWidgets.QLabel(self.centralwidget)
        self.Motor_1.setGeometry(QtCore.QRect(280, 30, 66, 17))
        self.Motor_1.setObjectName("Motor_1")
        self.Motor_2 = QtWidgets.QLabel(self.centralwidget)
        self.Motor_2.setGeometry(QtCore.QRect(280, 70, 66, 17))
        self.Motor_2.setObjectName("Motor_2")
        self.Motor_3 = QtWidgets.QLabel(self.centralwidget)
        self.Motor_3.setGeometry(QtCore.QRect(280, 110, 66, 17))
        self.Motor_3.setObjectName("Motor_3")
        self.Motor_4 = QtWidgets.QLabel(self.centralwidget)
        self.Motor_4.setGeometry(QtCore.QRect(280, 150, 66, 17))
        self.Motor_4.setObjectName("Motor_4")
        self.M1 = QtWidgets.QLineEdit(self.centralwidget)
        self.M1.setGeometry(QtCore.QRect(320, 30, 71, 21))
        self.M1.setObjectName("M1")
        self.M2 = QtWidgets.QLineEdit(self.centralwidget)
        self.M2.setGeometry(QtCore.QRect(320, 70, 71, 21))
        self.M2.setObjectName("M2")
        self.M3 = QtWidgets.QLineEdit(self.centralwidget)
        self.M3.setGeometry(QtCore.QRect(320, 110, 71, 21))
        self.M3.setObjectName("M3")
        self.M4 = QtWidgets.QLineEdit(self.centralwidget)
        self.M4.setGeometry(QtCore.QRect(320, 150, 71, 21))
        self.M4.setObjectName("M4")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(210, 380, 181, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(210, 420, 181, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.YPB = QtWidgets.QSlider(self.centralwidget)
        self.YPB.setGeometry(QtCore.QRect(100, 230, 161, 21))
        self.YPB.setOrientation(QtCore.Qt.Horizontal)
        self.YPB.setObjectName("YPB")
        self.YDB = QtWidgets.QSlider(self.centralwidget)
        self.YDB.setGeometry(QtCore.QRect(330, 230, 151, 21))
        self.YDB.setOrientation(QtCore.Qt.Horizontal)
        self.YDB.setObjectName("YDB")
        self.PPB = QtWidgets.QSlider(self.centralwidget)
        self.PPB.setGeometry(QtCore.QRect(100, 260, 161, 21))
        self.PPB.setOrientation(QtCore.Qt.Horizontal)
        self.PPB.setObjectName("PPB")
        self.PDB = QtWidgets.QSlider(self.centralwidget)
        self.PDB.setGeometry(QtCore.QRect(330, 260, 151, 21))
        self.PDB.setOrientation(QtCore.Qt.Horizontal)
        self.PDB.setObjectName("PDB")
        self.RPB = QtWidgets.QSlider(self.centralwidget)
        self.RPB.setGeometry(QtCore.QRect(100, 290, 161, 21))
        self.RPB.setOrientation(QtCore.Qt.Horizontal)
        self.RPB.setObjectName("RPB")
        self.RDB = QtWidgets.QSlider(self.centralwidget)
        self.RDB.setGeometry(QtCore.QRect(330, 290, 151, 21))
        self.RDB.setOrientation(QtCore.Qt.Horizontal)
        self.RDB.setObjectName("RDB")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(20, 260, 66, 17))
        self.label_7.setObjectName("label_7")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(20, 290, 66, 17))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(20, 230, 66, 17))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(20, 200, 66, 17))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(160, 200, 66, 17))
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(410, 200, 66, 17))
        self.label_16.setObjectName("label_16")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(10, 180, 621, 16))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.Battery = QtWidgets.QProgressBar(self.centralwidget)
        self.Battery.setGeometry(QtCore.QRect(520, 400, 111, 21))
        self.Battery.setMinimum(1050)
        self.Battery.setMaximum(1200)
        self.Battery.setProperty("value", 1200)
        self.Battery.setObjectName("Battery")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(410, 400, 101, 20))
        self.label_18.setObjectName("label_18")
        self.YP = QtWidgets.QLabel(self.centralwidget)
        self.YP.setGeometry(QtCore.QRect(270, 230, 21, 17))
        self.YP.setObjectName("YP")
        self.PP = QtWidgets.QLabel(self.centralwidget)
        self.PP.setGeometry(QtCore.QRect(270, 260, 21, 17))
        self.PP.setObjectName("PP")
        self.RP = QtWidgets.QLabel(self.centralwidget)
        self.RP.setGeometry(QtCore.QRect(270, 290, 21, 17))
        self.RP.setObjectName("RP")
        self.RD = QtWidgets.QLabel(self.centralwidget)
        self.RD.setGeometry(QtCore.QRect(490, 290, 21, 17))
        self.RD.setObjectName("RD")
        self.YD = QtWidgets.QLabel(self.centralwidget)
        self.YD.setGeometry(QtCore.QRect(490, 230, 21, 17))
        self.YD.setObjectName("YD")
        self.PD = QtWidgets.QLabel(self.centralwidget)
        self.PD.setGeometry(QtCore.QRect(490, 260, 21, 17))
        self.PD.setObjectName("PD")
        self.pushButtonMannul_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonMannul_2.setGeometry(QtCore.QRect(540, 280, 88, 25))
        self.pushButtonMannul_2.setObjectName("pushButtonMannul_2")
        self.pushButtonMannul_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonMannul_3.setGeometry(QtCore.QRect(540, 310, 88, 25))
        self.pushButtonMannul_3.setObjectName("pushButtonMannul_3")
        self.JCY = QtWidgets.QRadioButton(self.centralwidget)
        self.JCY.setGeometry(QtCore.QRect(30, 380, 41, 23))
        self.JCY.setAutoExclusive(False)
        self.JCY.setObjectName("JCY")
        self.JCN = QtWidgets.QRadioButton(self.centralwidget)
        self.JCN.setGeometry(QtCore.QRect(30, 410, 41, 23))
        self.JCN.setChecked(False)
        self.JCN.setAutoRepeat(False)
        self.JCN.setAutoExclusive(False)
        self.JCN.setObjectName("JCN")
        self.CCN = QtWidgets.QRadioButton(self.centralwidget)
        self.CCN.setGeometry(QtCore.QRect(140, 410, 41, 23))
        self.CCN.setChecked(False)
        self.CCN.setAutoRepeat(False)
        self.CCN.setAutoExclusive(False)
        self.CCN.setObjectName("CCN")
        self.CCY = QtWidgets.QRadioButton(self.centralwidget)
        self.CCY.setGeometry(QtCore.QRect(140, 380, 41, 23))
        self.CCY.setChecked(False)
        self.CCY.setAutoRepeat(False)
        self.CCY.setAutoExclusive(False)
        self.CCY.setObjectName("CCY")
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(20, 360, 81, 17))
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.centralwidget)
        self.label_20.setGeometry(QtCore.QRect(110, 360, 101, 17))
        self.label_20.setObjectName("label_20")
        self.Motor_5 = QtWidgets.QLabel(self.centralwidget)
        self.Motor_5.setGeometry(QtCore.QRect(220, 0, 66, 17))
        self.Motor_5.setObjectName("Motor_5")
        self.trim1 = QtWidgets.QLineEdit(self.centralwidget)
        self.trim1.setGeometry(QtCore.QRect(210, 30, 51, 25))
        self.trim1.setText("")
        self.trim1.setObjectName("trim1")
        self.trim2 = QtWidgets.QLineEdit(self.centralwidget)
        self.trim2.setGeometry(QtCore.QRect(210, 70, 51, 25))
        self.trim2.setObjectName("trim2")
        self.trim3 = QtWidgets.QLineEdit(self.centralwidget)
        self.trim3.setGeometry(QtCore.QRect(210, 110, 51, 25))
        self.trim3.setObjectName("trim3")
        self.trim4 = QtWidgets.QLineEdit(self.centralwidget)
        self.trim4.setGeometry(QtCore.QRect(210, 150, 51, 25))
        self.trim4.setObjectName("trim4")
        self.YP_2 = QtWidgets.QLabel(self.centralwidget)
        self.YP_2.setGeometry(QtCore.QRect(290, 230, 21, 17))
        self.YP_2.setObjectName("YP_2")
        self.YD_2 = QtWidgets.QLabel(self.centralwidget)
        self.YD_2.setGeometry(QtCore.QRect(510, 230, 21, 17))
        self.YD_2.setObjectName("YD_2")
        self.pushButtonRaw = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonRaw.setGeometry(QtCore.QRect(540, 370, 88, 25))
        self.pushButtonRaw.setObjectName("pushButtonRaw")
        self.pushButtonfull = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonfull.setGeometry(QtCore.QRect(540, 340, 88, 25))
        self.pushButtonfull.setObjectName("pushButtonfull")
        self.log_button = QtWidgets.QCommandLinkButton(self.centralwidget)
        self.log_button.setGeometry(QtCore.QRect(430, 320, 91, 41))
        self.log_button.setObjectName("log_button")
        self.show_figure = QtWidgets.QCheckBox(self.centralwidget)
        self.show_figure.setGeometry(QtCore.QRect(0, 330, 92, 23))
        self.show_figure.setObjectName("show_figure")
        self.PP_2 = QtWidgets.QLabel(self.centralwidget)
        self.PP_2.setGeometry(QtCore.QRect(290, 260, 21, 17))
        self.PP_2.setObjectName("PP_2")
        self.RP_2 = QtWidgets.QLabel(self.centralwidget)
        self.RP_2.setGeometry(QtCore.QRect(290, 290, 21, 17))
        self.RP_2.setObjectName("RP_2")
        self.PD_2 = QtWidgets.QLabel(self.centralwidget)
        self.PD_2.setGeometry(QtCore.QRect(510, 260, 21, 17))
        self.PD_2.setObjectName("PD_2")
        self.RD_2 = QtWidgets.QLabel(self.centralwidget)
        self.RD_2.setGeometry(QtCore.QRect(510, 290, 21, 17))
        self.RD_2.setObjectName("RD_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(290, 320, 66, 17))
        self.label.setObjectName("label")
        self.height = QtWidgets.QLabel(self.centralwidget)
        self.height.setGeometry(QtCore.QRect(290, 350, 66, 17))
        self.height.setText("")
        self.height.setObjectName("height")
        self.raw_show = QtWidgets.QPushButton(self.centralwidget)
        self.raw_show.setGeometry(QtCore.QRect(60, 310, 88, 25))
        self.raw_show.setObjectName("raw_show")
        self.ypr_show = QtWidgets.QPushButton(self.centralwidget)
        self.ypr_show.setGeometry(QtCore.QRect(60, 340, 88, 25))
        self.ypr_show.setObjectName("ypr_show")
        self.speed_show = QtWidgets.QPushButton(self.centralwidget)
        self.speed_show.setGeometry(QtCore.QRect(150, 310, 88, 25))
        self.speed_show.setObjectName("speed_show")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 640, 22))
        self.menubar.setObjectName("menubar")
        self.menuEXIT = QtWidgets.QMenu(self.menubar)
        self.menuEXIT.setObjectName("menuEXIT")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionEXIT = QtWidgets.QAction(MainWindow)
        self.actionEXIT.setObjectName("actionEXIT")
        self.menuEXIT.addAction(self.actionEXIT)
        self.menubar.addAction(self.menuEXIT.menuAction())

        self.retranslateUi(MainWindow)
        self.show_figure.clicked.connect(self.slot_figure_pressed)
        self.raw_show.pressed.connect(self.slot_raw_figure_pressed)
        self.ypr_show.pressed.connect(self.slot_ypr_figure_pressed)
        self.speed_show.pressed.connect(self.slot_speed_figure_pressed)
        self.pushButtonRaw.pressed.connect(self.slot_raw_pressed) # type: ignore
        self.pushButtonSafe.pressed.connect(self.slot_safe_pressed) # type: ignore
        self.pushButtonPanic.pressed.connect(self.slot_panic_pressed) # type: ignore
        self.pushButtonMannul.pressed.connect(self.slot_manual_pressed)
        self.pushButtonMannul_2.pressed.connect(self.slot_calibration_pressed) # type: ignore
        self.pushButtonMannul_3.pressed.connect(self.slot_yaw_pressed) # type: ignore
        self.pushButtonfull.pressed.connect(self.slot_full_pressed) # type: ignore
        self.log_button.pressed.connect(self.slot_log_pressed) # type: ignore
        self.YPB.sliderMoved['int'].connect(self.YP.setNum) # type: ignore
        self.PPB.sliderMoved['int'].connect(self.PP.setNum) # type: ignore
        self.RPB.sliderMoved['int'].connect(self.RP.setNum) # type: ignore
        # self.YIB.sliderMoved['int'].connect(self.YI.setNum) # type: ignore
        # self.PIB.sliderMoved['int'].connect(self.PI.setNum) # type: ignore
        # self.RIB.sliderMoved['int'].connect(self.RI.setNum) # type: ignore
        self.YDB.sliderMoved['int'].connect(self.YD.setNum) # type: ignore
        self.PDB.sliderMoved['int'].connect(self.PD.setNum) # type: ignore
        self.RDB.sliderMoved['int'].connect(self.RD.setNum) # type: ignore
        self.YPB.sliderMoved['int'].connect(self.slot_yaw_p_moved) # type: ignore
        self.YDB.sliderMoved['int'].connect(self.slot_yaw_d_moved) # type: ignore
        self.PPB.sliderMoved['int'].connect(self.slot_pitch_p_moved) # type: ignore
        self.PDB.sliderMoved['int'].connect(self.slot_pitch_d_moved) # type: ignore
        self.RPB.sliderMoved['int'].connect(self.slot_roll_p_moved) # type: ignore
        self.RDB.sliderMoved['int'].connect(self.slot_roll_d_moved) # type: ignore
        self.actionEXIT.toggled.connect(self.slot_exit) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        # Uncomment these lines to enable periodic reading from file
        self.reader_thread = FileReaderThread()
        self.reader_thread.data_updated.connect(self.update_ui)
        self.reader_thread.start()


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Group4-GUI"))
        self.JoyPitch.setText(_translate("MainWindow", "0"))
        self.label_2.setText(_translate("MainWindow", "Yaw"))
        self.JoyRoll.setText(_translate("MainWindow", "0"))
        self.DR.setText(_translate("MainWindow", "0"))
        self.JoyYaw.setText(_translate("MainWindow", "0"))
        self.DT.setText(_translate("MainWindow", "0"))
        self.label_3.setText(_translate("MainWindow", "Pitch"))
        self.joyT.setText(_translate("MainWindow", "0"))
        self.label_10.setText(_translate("MainWindow", "Throttle"))
        self.Joylabel.setText(_translate("MainWindow", "From Joystick"))
        self.label_8.setText(_translate("MainWindow", "Roll"))
        self.pushButtonSafe.setText(_translate("MainWindow", "Safe"))
        self.label_9.setText(_translate("MainWindow", "Mode"))
        self.pushButtonMannul.setText(_translate("MainWindow", "Manual"))
        self.label_5.setText(_translate("MainWindow", "Yaw"))
        self.DY.setText(_translate("MainWindow", "0"))
        self.Dronelabel.setText(_translate("MainWindow", "From Drone"))
        self.label_11.setText(_translate("MainWindow", "Throttle"))
        self.DP.setText(_translate("MainWindow", "0"))
        self.pushButtonPanic.setText(_translate("MainWindow", "Panic"))
        self.label_4.setText(_translate("MainWindow", "Roll"))
        self.label_6.setText(_translate("MainWindow", "Pitch"))
        self.Motor.setText(_translate("MainWindow", "Motor"))
        self.Motor_1.setText(_translate("MainWindow", "M1"))
        self.Motor_2.setText(_translate("MainWindow", "M2"))
        self.Motor_3.setText(_translate("MainWindow", "M3"))
        self.Motor_4.setText(_translate("MainWindow", "M4"))
        self.M1.setText(_translate("MainWindow", "NA"))
        self.M2.setText(_translate("MainWindow", "NA"))
        self.M3.setText(_translate("MainWindow", "NA"))
        self.M4.setText(_translate("MainWindow", "NA"))
        self.label_7.setText(_translate("MainWindow", "Pitch"))
        self.label_12.setText(_translate("MainWindow", "Roll"))
        self.label_13.setText(_translate("MainWindow", "Yaw"))
        self.label_14.setText(_translate("MainWindow", "PID"))
        self.label_15.setText(_translate("MainWindow", "P"))
        self.label_16.setText(_translate("MainWindow", "D"))
        self.label_18.setText(_translate("MainWindow", "Battery Status"))
        self.YP.setText(_translate("MainWindow", "0"))
        self.PP.setText(_translate("MainWindow", "0"))
        self.RP.setText(_translate("MainWindow", "0"))
        self.RD.setText(_translate("MainWindow", "0"))
        self.YD.setText(_translate("MainWindow", "0"))
        self.PD.setText(_translate("MainWindow", "0"))
        self.pushButtonMannul_2.setText(_translate("MainWindow", "Calibration"))
        self.pushButtonMannul_3.setText(_translate("MainWindow", "Yaw"))
        self.JCY.setText(_translate("MainWindow", "Y"))
        self.JCN.setText(_translate("MainWindow", "N"))
        self.CCN.setText(_translate("MainWindow", "N"))
        self.CCY.setText(_translate("MainWindow", "Y"))
        self.label_19.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:6pt;\">Joystick connection</span></p></body></html>"))
        self.label_20.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:6pt;\">Communication connection</span></p></body></html>"))
        self.Motor_5.setText(_translate("MainWindow", "Trim"))
        self.YP_2.setText(_translate("MainWindow", "0"))
        self.YD_2.setText(_translate("MainWindow", "0"))
        self.pushButtonRaw.setText(_translate("MainWindow", "Raw"))
        self.pushButtonfull.setText(_translate("MainWindow", "Full control"))
        self.log_button.setText(_translate("MainWindow", "Get Log"))
        self.show_figure.setText(_translate("MainWindow", "Show"))
        self.PP_2.setText(_translate("MainWindow", "0"))
        self.RP_2.setText(_translate("MainWindow", "0"))
        self.PD_2.setText(_translate("MainWindow", "0"))
        self.RD_2.setText(_translate("MainWindow", "0"))
        self.label.setText(_translate("MainWindow", "Height"))
        self.raw_show.setText(_translate("MainWindow", "raw_show"))
        self.ypr_show.setText(_translate("MainWindow", "ypr_show"))
        self.speed_show.setText(_translate("MainWindow", "speed_show"))
        self.menuEXIT.setTitle(_translate("MainWindow", "MENU"))
        self.actionEXIT.setText(_translate("MainWindow", "EXIT"))
    def update_ui(self, data):
        # Update UI elements with the received data
        if len(data) >= 25:
            self.DroneMode.setText(data[0])
            self.JoyPitch.setText(data[3])
            self.JoyRoll.setText(data[4])
            self.JoyYaw.setText(data[2])
            self.joyT.setText(data[5])
            self.DY.setText(data[7])
            self.DP.setText(data[8])
            self.DR.setText(data[9])
            self.DT.setText(data[10])
            self.trim1.setText(data[11])
            self.trim2.setText(data[12])
            self.trim3.setText(data[13])
            self.trim4.setText(data[14])
            self.M1.setText(data[15])
            self.M2.setText(data[16])
            self.M3.setText(data[17])
            self.M4.setText(data[18])
            self.YP_2.setText(data[19])
            self.YD_2.setText(data[20])
            self.PP_2.setText(data[21])
            self.PD_2.setText(data[22])
            self.RP_2.setText(data[23])
            self.RD_2.setText(data[24])
            self.Battery.setValue(int(data[25]))
            self.height.setText(data[26])
            if data[6] == "true":
                self.JCN.setChecked(True)
                self.JCY.setChecked(False)
            else:
                self.JCY.setChecked(True)
                self.JCN.setChecked(False)
            if data[0] == "Yaw Controlled":
                self.label_5.setText("Cal_Y")
                self.label_6.setText("Get_Y")
                self.label_8.setText("V")
            else:
                self.label_5.setText("Yaw")
                self.label_6.setText("Pitch")
                self.label_8.setText("Roll")



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    matplotlib.use('Qt5Agg')
    MainWindow.show()
    sys.exit(app.exec_())
